layout_spectrum: 0.4774436
color:
  saturation: 0.531441
  lightness: 0.534955
  brandStrength: 0.5068922
  brandColors:
    - '#040504'
    - '#9B9A99'
    - '#7F776E'
    - '#322704'
    - '#FFFFFF'
  rhythmicContrast: 0.9106877
typography_spectrum: 0.8057536
name: alex melcher
